#!/bin/csh -f
# $Id: patchN2WWW,v 2.2 1994/01/30 12:20:35 joke Rel $

foreach i ($argv)
  if ("$i" != "") then
    sed \
    -e 's|The Web|<A HREF="http://info.cern.ch/hypertext/DataSources/WWW/Geographical.html">The Web</A>|g' \
    -e 's|CERN|<A HREF="http://info.cern.ch/">CERN</A>|g' \
    -e 's|EUnet Deutschland|<A HREF="http://www.germany.eu.net/">EUnet Deutschland</A>|g' \
    -e 's|EUnet|<A HREF="http://www.eu.net/">EUnet</A>|g' \
    -e 's|World\-Wide Web project|<A HREF="http://info.cern.ch/hypertext/WWW/TheProject.html">World\-Wide Web project</A>|g' \
    -e 's|J\&ouml;rg Heitk\&ouml;tter|<A HREF="http://www.germany.eu.net/people/joke.html">J\&ouml;rg Heitk\&ouml;tter</A>|g' \
    -e 's|Ingo Dressler|<A HREF="http://www.germany.eu.net/people/id.html">Ingo Dre\&szlig;ler</A>|g' \
    -e 's|Rick Harris|<A HREF="http://www.vifp.monash.edu.au/people/rik.html">Rick Harris</A>|g' \
    -e 's|Dan Brown|<A HREF="http://www.eff.org/dan/dan.html">Dan Brown</A>|g' \
    -e 's|Otmar Lendl|<A HREF="http://www.cosy.sbg.ac.at/people/lendl.html">Otmar Lendl</A>|g' \
    -e 's|Jeff Dingbaum|<A HREF="http://www.hep.net/general/dingbaum/dingbaum.html">Jeff Dingbaum</A>|g' \
    -e 's|Roger Lighty|<A HREF="http://NewProducts.jpl.nasa.gov/people/lighty.html">Roger Lighty</A>|g' \
    -e 's|Holonet|<A HREF="http://www.holonet.net">Holonet</A>|g' \
    -e "s|Iain O'Cain|<A HREF="http://www.ais.org/~ec/">Iain O'Cain</A>|g" \
    < $i >/tmp/$i~
    mv /tmp/$i~ $i
  endif
end
